Repository markandey007/hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#55 Interpolation Search Program using C
  Interpolation_Search.c
Labels: hacktoberfest, hacktober-accepted, hacktoberfest-accepted

#82 Create Radix Sort
  Radix Sort
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#40 Create is_vowel.dart
  dart/is_vowel.dart
Labels: hacktoberfest-accepted
